import EuclidElements.Book10

/-!
# Euclid Book XI: synthetic solid geometry

Euclid gives definitions for solid geometry but no separate postulates.  The
incidence assumptions used implicitly in XI.1--XI.3 are therefore made explicit
here.  They are background structure of 3-space, not later proposition-shaped
shortcuts.
-/
namespace Euclid.Book11

structure SpaceGeometry where
  Point : Type
  Line : Type
  Plane : Type
  onLine : Point -> Line -> Prop
  onPlane : Point -> Plane -> Prop
  between : Point -> Point -> Point -> Prop
  perpLines : Line -> Line -> Prop
  parallelLines : Line -> Line -> Prop
  angleCongruent : Line -> Line -> Line -> Line -> Prop
  perpPlanes : Plane -> Plane -> Prop

variable {S : SpaceGeometry}

def LineInPlane (l : S.Line) (p : S.Plane) : Prop :=
  forall x, S.onLine x l -> S.onPlane x p

def LinesIntersectAt (l m : S.Line) (x : S.Point) : Prop :=
  S.onLine x l ∧ S.onLine x m ∧ l ≠ m

def LinesMeet (l m : S.Line) : Prop :=
  exists x, LinesIntersectAt l m x

def CoplanarLines (l m : S.Line) : Prop :=
  exists p, LineInPlane l p ∧ LineInPlane m p

def TriangleInPlane (a b c : S.Point) (p : S.Plane) : Prop :=
  S.onPlane a p ∧ S.onPlane b p ∧ S.onPlane c p

def PlanesMeet (p q : S.Plane) : Prop :=
  exists x, S.onPlane x p ∧ S.onPlane x q

def PlaneIntersectionIsLine (p q : S.Plane) (l : S.Line) : Prop :=
  p ≠ q ∧
  (forall x, S.onLine x l <-> (S.onPlane x p ∧ S.onPlane x q))

/-- Euclid XI.Def.3: a line is perpendicular to a plane when it is
perpendicular to every line in that plane through its foot. -/
def PerpendicularToPlane (l : S.Line) (p : S.Plane) : Prop :=
  exists x, S.onLine x l ∧ S.onPlane x p ∧
    forall m : S.Line, LineInPlane m p -> S.onLine x m -> S.perpLines l m

/-- Generic point-line incidence: two distinct points determine a unique straight line. -/
class SpatialLineIncidenceAxioms (S : SpaceGeometry) : Prop where
  through : forall {a b : S.Point}, a ≠ b ->
    exists l : S.Line, S.onLine a l /\ S.onLine b l
  unique : forall {a b : S.Point} {l m : S.Line}, a ≠ b ->
    S.onLine a l -> S.onLine b l -> S.onLine a m -> S.onLine b m -> l = m

/-- Solid incidence assumptions used implicitly in XI.1--XI.3. -/
class SolidIncidenceAxioms (S : SpaceGeometry) : Prop where
  lineClosure : forall {l : S.Line} {p : S.Plane} {a b : S.Point},
    a ≠ b -> S.onLine a l -> S.onLine b l -> S.onPlane a p -> S.onPlane b p ->
    LineInPlane l p
  intersectingLinesPlane : forall {l m : S.Line} {x : S.Point},
    LinesIntersectAt l m x -> exists p : S.Plane, LineInPlane l p ∧ LineInPlane m p
  threePointsPlane : forall {a b c : S.Point},
    exists p : S.Plane, TriangleInPlane a b c p
  planeIntersection : forall {p q : S.Plane},
    p ≠ q -> PlanesMeet p q -> exists l : S.Line, PlaneIntersectionIsLine p q l

/-- Orthogonality principle for a plane generated by two intersecting lines.
This is the synthetic 3D linearity fact used by XI.4. -/
class PlaneOrthogonalityAxioms (S : SpaceGeometry) : Prop where
  generatedPlaneCriterion : forall {l m n : S.Line} {x : S.Point} {p : S.Plane},
    LinesIntersectAt m n x ->
    LineInPlane m p -> LineInPlane n p ->
    S.onLine x l -> S.perpLines l m -> S.perpLines l n ->
    forall r : S.Line, LineInPlane r p -> S.onLine x r -> S.perpLines l r


/-- Generic direction laws for lines and plane normals in 3-space.  These give
semantic content to the primitive parallel-line relation without baking in any
single Book XI proposition. -/
class SpatialDirectionAxioms (S : SpaceGeometry) : Prop where
  parallelCoplanar : forall {l m : S.Line},
    S.parallelLines l m -> CoplanarLines l m
  parallelSymm : forall {l m : S.Line},
    S.parallelLines l m -> S.parallelLines m l
  parallelTrans : forall {l m n : S.Line},
    S.parallelLines l m -> S.parallelLines m n -> S.parallelLines l n
  normalsParallel : forall {l m : S.Line} {p : S.Plane},
    PerpendicularToPlane l p -> PerpendicularToPlane m p -> S.parallelLines l m
  parallelPreservesNormal : forall {l m : S.Line} {p : S.Plane},
    S.parallelLines l m -> PerpendicularToPlane l p -> PerpendicularToPlane m p
  perpendicularThroughFootLiesInPlane : forall {l m : S.Line} {p : S.Plane} {x : S.Point},
    PerpendicularToPlane l p -> S.onLine x l -> S.onPlane x p ->
    S.onLine x m -> S.perpLines l m -> LineInPlane m p
  parallelPairsPreserveAngle : forall {l m l' m' : S.Line},
    S.parallelLines l l' -> S.parallelLines m m' ->
    S.angleCongruent l m l' m'
  parallelFirstSameSecondAngle : forall {l l' m : S.Line},
    S.parallelLines l l' -> S.angleCongruent l m l' m
  parallelSecondSameFirstAngle : forall {l m m' : S.Line},
    S.parallelLines m m' -> S.angleCongruent l m l m'


/-- XI.Def.8: parallel planes are planes which do not meet. -/
def ParallelPlanes (p q : S.Plane) : Prop :=
  Not (PlanesMeet p q)

/-- XI.Def.4 represented as the primitive perpendicular-plane relation carried
by the solid model. -/
def PerpendicularPlanes (p q : S.Plane) : Prop := S.perpPlanes p q

/-- Generic construction and uniqueness laws for normals to a plane.  These
express the ordinary incidence/construction content Euclid uses in XI.11--13. -/
class PlaneNormalConstructionAxioms (S : SpaceGeometry) : Prop where
  fromElevatedPoint : forall {a : S.Point} {p : S.Plane},
    Not (S.onPlane a p) ->
    exists l : S.Line, S.onLine a l ∧ PerpendicularToPlane l p
  atPoint : forall {a : S.Point} {p : S.Plane},
    S.onPlane a p ->
    exists l : S.Line, S.onLine a l ∧ PerpendicularToPlane l p
  uniqueThroughPoint : forall {a : S.Point} {p : S.Plane} {l m : S.Line},
    S.onLine a l -> S.onLine a m ->
    PerpendicularToPlane l p -> PerpendicularToPlane m p ->
    l = m

/-- Plane-direction laws needed after perpendiculars and parallel planes have
been introduced.  They state generic incidence behavior of planes in 3-space,
not construction data tied to a particular diagram. -/
class PlaneDirectionAxioms (S : SpaceGeometry) : Prop where
  normalsGiveParallelPlanes : forall {l : S.Line} {p q : S.Plane},
    PerpendicularToPlane l p -> PerpendicularToPlane l q -> ParallelPlanes p q
  parallelPairsGiveParallelPlanes : forall
      {l m l' m' : S.Line} {x y : S.Point} {p q : S.Plane},
    LinesIntersectAt l m x -> LinesIntersectAt l' m' y ->
    LineInPlane l p -> LineInPlane m p ->
    LineInPlane l' q -> LineInPlane m' q ->
    S.parallelLines l l' -> S.parallelLines m m' ->
    ParallelPlanes p q
  sectionsOfParallelPlanes : forall {p q r : S.Plane} {l m : S.Line},
    ParallelPlanes p q ->
    PlaneIntersectionIsLine p r l -> PlaneIntersectionIsLine q r m ->
    S.parallelLines l m
  planeThroughNormalPerpendicular : forall {l : S.Line} {p q : S.Plane},
    LineInPlane l p -> PerpendicularToPlane l q -> PerpendicularPlanes p q


/-- Synthetic magnitudes for spatial line segments.  This is the Book XI
analogue of the Book VI segment-magnitude bridge. -/
class SpatialSegmentMagnitude (S : SpaceGeometry) where
  Magnitude : Type
  magnitudeStructure : Euclid.Book5.MagnitudeStructure Magnitude
  magnitudeAxioms : Euclid.Book5.MagnitudeAxioms Magnitude
  eudoxusSeparation : Euclid.Book5.EudoxusSeparationAxioms Magnitude
  length : S.Point -> S.Point -> Magnitude
  positive : forall {a b : S.Point}, a ≠ b ->
    Euclid.Book5.Positive (length a b)
  symmetric : forall a b : S.Point, length a b = length b a

attribute [instance] SpatialSegmentMagnitude.magnitudeStructure
attribute [instance] SpatialSegmentMagnitude.magnitudeAxioms
attribute [instance] SpatialSegmentMagnitude.eudoxusSeparation


/-- Orientation-free order facts for a point lying between two endpoints. -/
class SpatialBetweennessAxioms (S : SpaceGeometry) : Prop where
  reverse : forall {a b c : S.Point}, S.between a b c -> S.between c b a

/-- Segment addition for an interior point.  This is the spatial transport of
Euclid's common notion that a whole segment is the sum of its adjacent parts. -/
class SpatialSegmentAdditionAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] : Prop where
  add_of_between : forall {a b c : S.Point}, S.between a b c ->
    Euclid.Book5.Add (L.length a b) (L.length b c) = L.length a c

/-- Euclid's subtraction step: from D-E-H-K in order and DH = EK, subtract
the common middle segment EH to obtain DE = HK. -/
theorem equalRemainders_of_nestedSegments (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [SA : SpatialSegmentAdditionAxioms S]
    {d e h k : S.Point}
    (hdeh : S.between d e h) (hehk : S.between e h k)
    (hwhole : L.length d h = L.length e k) :
    L.length d e = L.length h k := by
  have h1 := SA.add_of_between hdeh
  have h2 := SA.add_of_between hehk
  have h2' : Euclid.Book5.Add (L.length h k) (L.length e h) = L.length e k := by
    calc
      Euclid.Book5.Add (L.length h k) (L.length e h) =
          Euclid.Book5.Add (L.length e h) (L.length h k) :=
            Euclid.Book5.MagnitudeAxioms.addComm _ _
      _ = L.length e k := h2
  apply Euclid.Book5.MagnitudeAxioms.addCancelRight
  exact h1.trans (hwhole.trans h2'.symm)

/-- VI.2 transported to any plane in the solid model: a line parallel to one
side of a triangle cuts the other two sides proportionally.  This is a generic
planar theorem bridge, not an XI.17-specific ratio assertion. -/
class PlanarParallelCutAxioms (S : SpaceGeometry)
    [SpatialSegmentMagnitude S] : Prop where
  parallelCut : forall
    {v e b f d : S.Point} {vb vd ef bd : S.Line} {p : S.Plane},
    S.between v e b -> S.between v f d ->
    S.onLine v vb -> S.onLine e vb -> S.onLine b vb ->
    S.onLine v vd -> S.onLine f vd -> S.onLine d vd ->
    S.onLine e ef -> S.onLine f ef ->
    S.onLine b bd -> S.onLine d bd ->
    LineInPlane vb p -> LineInPlane vd p ->
    LineInPlane ef p -> LineInPlane bd p ->
    S.parallelLines ef bd ->
    Euclid.Book5.SameRatio
      (SpatialSegmentMagnitude.length v e)
      (SpatialSegmentMagnitude.length e b)
      (SpatialSegmentMagnitude.length v f)
      (SpatialSegmentMagnitude.length f d)


/-- Generic semantic law for orthogonal planes: if two planes are both
perpendicular to a third and meet in a line, that common intersection line is
normal to the third plane.  This is the 3D orthogonality law underlying XI.19,
kept at the plane-relation level rather than tied to Euclid's diagram names. -/
class OrthogonalPlaneIntersectionAxioms (S : SpaceGeometry) : Prop where
  commonIntersectionNormal : forall {p q r : S.Plane} {l : S.Line},
    PerpendicularPlanes p r -> PerpendicularPlanes q r ->
    PlaneIntersectionIsLine p q l ->
    PerpendicularToPlane l r

/-- One plane angle at a vertex, represented by its two rays. -/
structure PlaneAngle3D (S : SpaceGeometry) where
  vertex : S.Point
  side1 : S.Line
  side2 : S.Line
  onSide1 : S.onLine vertex side1
  onSide2 : S.onLine vertex side2

/-- Three plane angles around one vertex.  This records only incidence;
XI.20--XI.23 must supply the nontrivial metric/angle facts separately. -/
structure TrihedralAngle (S : SpaceGeometry) where
  vertex : S.Point
  ray1 : S.Line
  ray2 : S.Line
  ray3 : S.Line
  on1 : S.onLine vertex ray1
  on2 : S.onLine vertex ray2
  on3 : S.onLine vertex ray3
  distinct12 : ray1 ≠ ray2
  distinct23 : ray2 ≠ ray3
  distinct31 : ray3 ≠ ray1


/-- Synthetic magnitudes for plane angles in solid geometry.  The values are
abstract angle magnitudes, not real-number measures. -/
class SpatialAngleMagnitude (S : SpaceGeometry) where
  Magnitude : Type
  zero : Magnitude
  add : Magnitude -> Magnitude -> Magnitude
  lt : Magnitude -> Magnitude -> Prop
  right : Magnitude
  angle : S.Line -> S.Line -> Magnitude
  addAssoc : forall a b c, add (add a b) c = add a (add b c)
  addComm : forall a b, add a b = add b a
  ltTrans : forall {a b c}, lt a b -> lt b c -> lt a c
  addLtAddRight : forall {a b} c, lt a b -> lt (add a c) (add b c)
  congruent_iff : forall {l m l' m'},
    S.angleCongruent l m l' m' <-> angle l m = angle l' m'

/-- Irreflexivity of the strict angle order, exposed as a generic semantic law. -/
class SpatialAngleOrderAxioms (S : SpaceGeometry) [A : SpatialAngleMagnitude S] : Prop where
  ltIrrefl : forall a : A.Magnitude, Not (A.lt a a)

theorem angle_lt_irrefl (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S] [O : SpatialAngleOrderAxioms S]
    (a : A.Magnitude) : Not (A.lt a a) := O.ltIrrefl a

/-- Sum of the three face-angles of a trihedral angle. -/
def TrihedralAngleSum (S : SpaceGeometry) [A : SpatialAngleMagnitude S]
    (t : TrihedralAngle S) : A.Magnitude :=
  A.add (A.angle t.ray1 t.ray2)
    (A.add (A.angle t.ray2 t.ray3) (A.angle t.ray3 t.ray1))

/-- The two numerical conditions singled out by XI.20 and XI.21.  This is a
definition only; no existence theorem is assumed here. -/
def AdmissibleTrihedralAngles (S : SpaceGeometry) [A : SpatialAngleMagnitude S]
    (x y z : A.Magnitude) : Prop :=
  A.lt x (A.add y z) ∧
  A.lt y (A.add z x) ∧
  A.lt z (A.add x y) ∧
  A.lt (A.add x (A.add y z))
    (A.add (A.add A.right A.right) (A.add A.right A.right))


/-- Generic metric laws for angular distance between rays.  XI.20 is the
ordinary triangle inequality in this angular metric. -/
class RayAngleMetricAxioms (S : SpaceGeometry) [A : SpatialAngleMagnitude S] : Prop where
  triangle : forall l m n : S.Line,
    A.lt (A.angle l m) (A.add (A.angle l n) (A.angle n m))
  symmetric : forall l m : S.Line, A.angle l m = A.angle m l

/-- A trihedral angle is convex when its three rays bound an ordinary solid
angle rather than wrapping around the vertex.  The four-right-angle perimeter
bound is a generic property of convex spherical/ray triangles. -/
class ConvexTrihedralGeometry (S : SpaceGeometry) [A : SpatialAngleMagnitude S] where
  Convex : TrihedralAngle S -> Prop
  perimeter_lt_four_right : forall t : TrihedralAngle S,
    Convex t ->
    A.lt (TrihedralAngleSum S t)
      (A.add (A.add A.right A.right) (A.add A.right A.right))

/-- Three abstract angle magnitudes satisfy the XI.20 pairwise conditions. -/
def PairwiseAngleTriangleInequalities (S : SpaceGeometry) [A : SpatialAngleMagnitude S]
    (x y z : A.Magnitude) : Prop :=
  A.lt x (A.add y z) ∧
  A.lt y (A.add z x) ∧
  A.lt z (A.add x y)


/-- Ordered additive structure for spatial segment magnitudes, sufficient to
state the three side inequalities required by I.22. -/
class SpatialSegmentOrderMagnitude (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] where
  add : L.Magnitude -> L.Magnitude -> L.Magnitude
  lt : L.Magnitude -> L.Magnitude -> Prop
  addComm : forall a b, add a b = add b a
  add_eq_book5 : forall a b,
    add a b = Euclid.Book5.Add a b
  lt_iff_book5 : forall a b,
    lt a b <-> Euclid.Book5.Less a b

/-- The three strict inequalities characterizing admissible side lengths of a
(non-degenerate) triangle. -/
def TriangleSideInequalities (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [O : SpatialSegmentOrderMagnitude S]
    (a b c : L.Magnitude) : Prop :=
  O.lt a (O.add b c) ∧ O.lt b (O.add c a) ∧ O.lt c (O.add a b)

/-- Chords subtended by equal radii depend only on the included angle.  The
transfer law packages the reusable equal-radius chord comparison behind XI.22:
angular triangle inequalities imply the corresponding chord triangle
inequalities.  This is intentionally stated independently of any Book-XI
diagram. -/
class EqualRadiusChordGeometry (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [O : SpatialSegmentOrderMagnitude S] where
  chord : A.Magnitude -> L.Magnitude
  chord_positive : forall x : A.Magnitude, Euclid.Book5.Positive (chord x)
  triangleTransfer : forall {x y z : A.Magnitude},
    PairwiseAngleTriangleInequalities S x y z ->
    TriangleSideInequalities S (chord x) (chord y) (chord z)


/-- Position of the circumcenter relative to the base triangle.  XI.23 needs
all three cases, not only Euclid's interior case. -/
inductive CircumcenterPosition where
  | inside
  | boundary
  | outside

/-- Generic construction of a spatial triangle with prescribed side
magnitudes.  This is the 3D analogue of I.22 and is independent of XI.23. -/
class SpatialTriangleConstructionAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S]
    [O : SpatialSegmentOrderMagnitude S] where
  construct : forall {a b c : L.Magnitude},
    TriangleSideInequalities S a b c ->
    exists A B C : S.Point, exists AB BC CA : S.Line, exists p : S.Plane,
      A ≠ B /\ B ≠ C /\ C ≠ A /\
      S.onLine A AB /\ S.onLine B AB /\
      S.onLine B BC /\ S.onLine C BC /\
      S.onLine C CA /\ S.onLine A CA /\
      LineInPlane AB p /\ LineInPlane BC p /\ LineInPlane CA p /\
      L.length A B = a /\ L.length B C = b /\ L.length C A = c

/-- Generic circumcenter construction/classification for a nondegenerate
spatial triangle lying in a plane. -/
class SpatialCircumcenterAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] where
  circumcenter : forall {A B C : S.Point} {p : S.Plane},
    S.onPlane A p -> S.onPlane B p -> S.onPlane C p ->
    A ≠ B -> B ≠ C -> C ≠ A ->
    exists Ctr : S.Point, exists pos : CircumcenterPosition,
      S.onPlane Ctr p /\
      L.length Ctr A = L.length Ctr B /\
      L.length Ctr A = L.length Ctr C

/-- Common-edge magnitude used in XI.23.  All three proposed face angles
are cut with the same edge length; this is construction data, not a radius
comparison theorem. -/
class TrihedralCommonEdgeGeometry (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S] where
  edge : A.Magnitude -> L.Magnitude
  edge_eq : forall x y : A.Magnitude, edge x = edge y
  edge_positive : forall x : A.Magnitude, Euclid.Book5.Positive (edge x)

/-- Spatial analogue of Book III's chord/central-angle metric semantics.
If two radii have the common construction length and their joining chord is
the chord assigned to angle `x`, the central angle has magnitude `x`. -/
class SpatialChordCentralAngleAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S] where
  centralAngle : S.Point -> S.Point -> S.Point -> A.Magnitude
  recover : forall {x : A.Magnitude} {O P Q : S.Point},
    L.length O P = E.edge x ->
    L.length O Q = E.edge x ->
    L.length P Q = C.chord x ->
    centralAngle O P Q = x

/-- Full-turn law for three consecutive central angles determined by three
points on one circle.  The circumcenter-position parameter keeps explicit the
inside/boundary/outside cases that Euclid's written XI.23 proof suppresses. -/
class SpatialCentralAngleFullTurnAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S] where
  sum_four_right : forall {O P Q R : S.Point} {pos : CircumcenterPosition},
    L.length O P = L.length O Q ->
    L.length O P = L.length O R ->
    A.add (CA.centralAngle O P Q)
      (A.add (CA.centralAngle O Q R) (CA.centralAngle O R P)) =
      A.add (A.add A.right A.right) (A.add A.right A.right)

/-- Equality of circumradius and common proposed edge is impossible: the three
chord-central-angle recoveries would turn the strict XI.21 hypothesis into
`four right < four right`. -/
theorem circumradius_ne_edge (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [AO : SpatialAngleOrderAxioms S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S]
    [FT : SpatialCentralAngleFullTurnAxioms S]
    {x y z : A.Magnitude}
    {P Q R Ctr : S.Point} {pos : CircumcenterPosition}
    (h : AdmissibleTrihedralAngles S x y z)
    (hPQ : L.length P Q = C.chord x)
    (hQR : L.length Q R = C.chord y)
    (hRP : L.length R P = C.chord z)
    (hCP_CQ : L.length Ctr P = L.length Ctr Q)
    (hCP_CR : L.length Ctr P = L.length Ctr R) :
    L.length Ctr P ≠ E.edge x := by
  intro heq
  have hCQx : L.length Ctr Q = E.edge x := hCP_CQ.symm.trans heq
  have hCRx : L.length Ctr R = E.edge x := hCP_CR.symm.trans heq
  have hxy : E.edge x = E.edge y := E.edge_eq x y
  have hxz : E.edge x = E.edge z := E.edge_eq x z
  have hPQang : CA.centralAngle Ctr P Q = x :=
    CA.recover heq hCQx hPQ
  have hQRang : CA.centralAngle Ctr Q R = y := by
    apply CA.recover
    · exact hCQx.trans hxy
    · exact hCRx.trans hxy
    · exact hQR
  have hRPang : CA.centralAngle Ctr R P = z := by
    apply CA.recover
    · exact hCRx.trans hxz
    · exact heq.trans hxz
    · exact hRP
  have hfull := FT.sum_four_right (pos := pos) hCP_CQ hCP_CR
  rw [hPQang, hQRang, hRPang] at hfull
  have hlt := h.2.2.2
  rw [hfull] at hlt
  -- strict angle order is irreflexive; derive it from transitivity by a
  -- one-step semantic law below rather than numeric angle measures.
  exact angle_lt_irrefl S _ hlt

/-- Euclid XI.23's inner-triangle construction for the case where the
common proposed edge is shorter than the circumradius.  Points `P'`,`Q'` are
cut off on the two radii with the prescribed common edge length, and their
joining line is parallel to the original chord.  This is the construction/
parallelism content of I.3 + VI.2/I.29, with no angle comparison built in. -/
class InnerParallelChordConstructionAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [E : TrihedralCommonEdgeGeometry S] where
  construct : forall {x : A.Magnitude} {O P Q : S.Point},
    L.length O P = L.length O Q ->
    Ord.lt (E.edge x) (L.length O P) ->
    exists P' Q' : S.Point, exists OP OQ PQ P'Q' : S.Line, exists p : S.Plane,
      S.between O P' P /\ S.between O Q' Q /\
      P' ≠ Q' /\
      S.onLine O OP /\ S.onLine P' OP /\ S.onLine P OP /\
      S.onLine O OQ /\ S.onLine Q' OQ /\ S.onLine Q OQ /\
      S.onLine P PQ /\ S.onLine Q PQ /\
      S.onLine P' P'Q' /\ S.onLine Q' P'Q' /\
      LineInPlane OP p /\ LineInPlane OQ p /\
      LineInPlane PQ p /\ LineInPlane P'Q' p /\
      S.parallelLines P'Q' PQ /\
      L.length O P' = E.edge x /\ L.length O Q' = E.edge x

/-- VI.4 plane-restriction bridge for the two homothetic triangles in
XI.23.  It supplies only the proportion; the strict base comparison is derived
below from Book V.14 rather than assumed. -/
class ParallelTriangleRatioAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] : Prop where
  ratio : forall
      {O P Q P' Q' : S.Point} {OP OQ PQ P'Q' : S.Line} {p : S.Plane},
    S.between O P' P -> S.between O Q' Q ->
    S.onLine O OP -> S.onLine P' OP -> S.onLine P OP ->
    S.onLine O OQ -> S.onLine Q' OQ -> S.onLine Q OQ ->
    S.onLine P PQ -> S.onLine Q PQ ->
    S.onLine P' P'Q' -> S.onLine Q' P'Q' ->
    LineInPlane OP p -> LineInPlane OQ p ->
    LineInPlane PQ p -> LineInPlane P'Q' p ->
    S.parallelLines P'Q' PQ ->
    Euclid.Book5.SameRatio
      (L.length O P) (L.length P Q)
      (L.length O P') (L.length P' Q')

/-- V.14 turns the VI.4 proportion into the strict base comparison used by
XI.23.  Thus order transport is proved from Book V rather than included in the
plane bridge. -/
theorem parallelTriangle_innerBaseLt (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [R : ParallelTriangleRatioAxioms S]
    {O P Q P' Q' : S.Point} {OP OQ PQ P'Q' : S.Line} {p : S.Plane}
    (hPP : S.between O P' P) (hQQ : S.between O Q' Q)
    (hP'neQ' : P' ≠ Q')
    (hOOP : S.onLine O OP) (hP'OP : S.onLine P' OP) (hPOP : S.onLine P OP)
    (hOOQ : S.onLine O OQ) (hQ'OQ : S.onLine Q' OQ) (hQOQ : S.onLine Q OQ)
    (hPPQ : S.onLine P PQ) (hQPQ : S.onLine Q PQ)
    (hP'P'Q' : S.onLine P' P'Q') (hQ'P'Q' : S.onLine Q' P'Q')
    (hOPp : LineInPlane OP p) (hOQp : LineInPlane OQ p)
    (hPQp : LineInPlane PQ p) (hP'Q'p : LineInPlane P'Q' p)
    (hpar : S.parallelLines P'Q' PQ)
    (hsmall : Ord.lt (L.length O P') (L.length O P))
    (hOuterBasePos : Euclid.Book5.Positive (L.length P Q))
    (hInnerRadiusPos : Euclid.Book5.Positive (L.length O P')) :
    Ord.lt (L.length P' Q') (L.length P Q) := by
  have hratio := R.ratio hPP hQQ hOOP hP'OP hPOP hOOQ hQ'OQ hQOQ
    hPPQ hQPQ hP'P'Q' hQ'P'Q' hOPp hOQp hPQp hP'Q'p hpar
  have hOuterRadiusPos : Euclid.Book5.Positive (L.length O P) :=
    Euclid.Book5.MagnitudeAxioms.ltTrans hInnerRadiusPos ((Ord.lt_iff_book5 _ _).1 hsmall)
  have hInnerBasePos : Euclid.Book5.Positive (L.length P' Q') := L.positive hP'neQ'
  have hcmp := Euclid.Book5.proposition14 L.Magnitude
    hOuterRadiusPos hOuterBasePos hInnerRadiusPos hInnerBasePos hratio
  exact (Ord.lt_iff_book5 _ _).2 (hcmp.1 ((Ord.lt_iff_book5 _ _).1 hsmall))

/-- Moving endpoints along the same two rays from a center does not change
the included central angle.  This is pure ray/angle semantics, independent of
metric comparison. -/
class CentralAngleRayInvarianceAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S] : Prop where
  alongRays : forall {O P Q P' Q' : S.Point},
    S.between O P' P -> S.between O Q' Q ->
    CA.centralAngle O P' Q' = CA.centralAngle O P Q

/-- A complete 2D Book-I environment used to restrict one spatial plane
back to the already formalized synthetic plane theory.  The fields are the
standard reusable Book-I background structures required by I.25; no hinge
conclusion is stored here. -/
structure Book1HingeModel where
  G : Euclid.Geometry
  postulates : Euclid.Book1.Postulates G
  implicit : Euclid.Book1.ImplicitAxioms G
  proposition2 : Euclid.Book1.Proposition2ImplicitAxioms G
  segmentOrder : Euclid.Book1.SegmentOrder G
  segmentSum : Euclid.Book1.SegmentSumGeometry G
  triangleArea : Euclid.Book1.TriangleAreaGeometry G
  angleSum : Euclid.Book1.AngleSumGeometry G
  angleInterior : Euclid.Book1.AngleInteriorGeometry G
  triangleInterior : Euclid.Book1.TriangleInteriorGeometry G
  later : @Euclid.Book1.LaterImplicitAxioms G segmentOrder triangleArea
  angleImplicit : @Euclid.Book1.AngleImplicitAxioms G angleSum
  angleOrder : @Euclid.Book1.AngleOrderImplicitAxioms G angleInterior
  proposition16 : @Euclid.Book1.Proposition16ImplicitAxioms G triangleInterior angleInterior
  segmentArithmetic : @Euclid.Book1.SegmentArithmeticImplicitAxioms G segmentOrder segmentSum
  triangleConstruction : @Euclid.Book1.TriangleConstructionImplicitAxioms G segmentSum
  angleRayConstruction : @Euclid.Book1.AngleRayConstructionAxioms G angleInterior

/-- Plane-restriction witness for the specific pair of equal-side triangles
used in XI.23.  It supplies the two triangles and bridge facts needed to feed
them to the existing Book-I theorem I.25.  The angle inequality itself is not
a field: it will be produced by `Book1.proposition25`. -/
class PlaneHingeWitnessAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S] where
  witness : forall {x : A.Magnitude} {O P Q : S.Point},
    L.length O P = E.edge x ->
    L.length O Q = E.edge x ->
    Ord.lt (L.length P Q) (C.chord x) ->
    exists M : Book1HingeModel,
    exists A0 B0 C0 D0 E0 F0 : M.G.Point,
      Euclid.Book1.IsTriangle M.G A0 B0 C0 /\
      Euclid.Book1.IsTriangle M.G D0 E0 F0 /\
      M.G.segmentCongruent A0 B0 D0 E0 /\
      M.G.segmentCongruent A0 C0 D0 F0 /\
      @Euclid.Book1.SegmentLess M.G M.segmentOrder E0 F0 B0 C0 /\
      (M.G.angleLess ⟨E0, D0, F0⟩ ⟨B0, A0, C0⟩ ->
        A.lt (CA.centralAngle O P Q) x)

/-- Invoke the already formalized Euclid I.25 inside the restricted plane and
transport its conclusion back to the spatial central-angle magnitude. -/
theorem spatialHingeComparison_from_Book1 (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S]
    [W : PlaneHingeWitnessAxioms S]
    {x : A.Magnitude} {O P Q : S.Point}
    (hOP : L.length O P = E.edge x)
    (hOQ : L.length O Q = E.edge x)
    (hbase : Ord.lt (L.length P Q) (C.chord x)) :
    A.lt (CA.centralAngle O P Q) x := by
  obtain ⟨M, A0, B0, C0, D0, E0, F0,
      hABC, hDEF, hAB_DE, hAC_DF, hEF_BC, hbridge⟩ :=
    W.witness hOP hOQ hbase
  letI : Euclid.Book1.Postulates M.G := M.postulates
  letI : Euclid.Book1.ImplicitAxioms M.G := M.implicit
  letI : Euclid.Book1.Proposition2ImplicitAxioms M.G := M.proposition2
  letI : Euclid.Book1.SegmentOrder M.G := M.segmentOrder
  letI : Euclid.Book1.SegmentSumGeometry M.G := M.segmentSum
  letI : Euclid.Book1.TriangleAreaGeometry M.G := M.triangleArea
  letI : Euclid.Book1.AngleSumGeometry M.G := M.angleSum
  letI : Euclid.Book1.AngleInteriorGeometry M.G := M.angleInterior
  letI : Euclid.Book1.TriangleInteriorGeometry M.G := M.triangleInterior
  letI : Euclid.Book1.LaterImplicitAxioms M.G := M.later
  letI : Euclid.Book1.AngleImplicitAxioms M.G := M.angleImplicit
  letI : Euclid.Book1.AngleOrderImplicitAxioms M.G := M.angleOrder
  letI : Euclid.Book1.Proposition16ImplicitAxioms M.G := M.proposition16
  letI : Euclid.Book1.SegmentArithmeticImplicitAxioms M.G := M.segmentArithmetic
  letI : Euclid.Book1.TriangleConstructionImplicitAxioms M.G := M.triangleConstruction
  letI : Euclid.Book1.AngleRayConstructionAxioms M.G := M.angleRayConstruction
  have h25 : M.G.angleLess ⟨E0, D0, F0⟩ ⟨B0, A0, C0⟩ :=
    Euclid.Book1.proposition25 M.G hABC hDEF hAB_DE hAC_DF hEF_BC
  exact hbridge h25

/-- Fixed-chord radius monotonicity derived in the same stages as Euclid XI.23:
construct the inner parallel chord, compare its base with the outer chord by
VI.2/VI.4/V.16, apply I.25 to the equal-edge inner triangle, and finally move
back to the original rays. -/
theorem fixedChordRadiusAngleMonotonicity (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S]
    [IC : InnerParallelChordConstructionAxioms S]
    [R : ParallelTriangleRatioAxioms S]
    [RI : CentralAngleRayInvarianceAxioms S]
    [W : PlaneHingeWitnessAxioms S]
    {x : A.Magnitude} {O P Q : S.Point}
    (hradii : L.length O P = L.length O Q)
    (hchord : L.length P Q = C.chord x)
    (hsmall : Ord.lt (E.edge x) (L.length O P)) :
    A.lt (CA.centralAngle O P Q) x := by
  obtain ⟨P', Q', OP, OQ, PQ, P'Q', p,
      hPP, hQQ, hP'neQ', hOOP, hP'OP, hPOP, hOOQ, hQ'OQ, hQOQ,
      hPPQ, hQPQ, hP'P'Q', hQ'P'Q', hOPp, hOQp, hPQp, hP'Q'p,
      hpar, hOP', hOQ'⟩ := IC.construct hradii hsmall
  have hinnerRadiusPos : Euclid.Book5.Positive (L.length O P') := by
    rw [hOP']
    exact E.edge_positive x
  have hOuterBasePos : Euclid.Book5.Positive (L.length P Q) := by
    rw [hchord]
    exact C.chord_positive x
  have hinnerLtOuter : Ord.lt (L.length P' Q') (L.length P Q) :=
    parallelTriangle_innerBaseLt S hPP hQQ hP'neQ' hOOP hP'OP hPOP
      hOOQ hQ'OQ hQOQ hPPQ hQPQ hP'P'Q' hQ'P'Q' hOPp hOQp hPQp
      hP'Q'p hpar (by rw [hOP']; exact hsmall) hOuterBasePos hinnerRadiusPos
  have hinnerLtChord : Ord.lt (L.length P' Q') (C.chord x) := by
    rw [← hchord]
    exact hinnerLtOuter
  have hinnerAngle : A.lt (CA.centralAngle O P' Q') x :=
    spatialHingeComparison_from_Book1 S hOP' hOQ' hinnerLtChord
  have hray := RI.alongRays hPP hQQ
  rw [hray] at hinnerAngle
  exact hinnerAngle

/-- Strict addition on the left, derived from commutativity and the primitive
right-addition order law for abstract angle magnitudes. -/
theorem angle_add_lt_add_left (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    {a b : A.Magnitude} (c : A.Magnitude) (h : A.lt a b) :
    A.lt (A.add c a) (A.add c b) := by
  rw [A.addComm c a, A.addComm c b]
  exact A.addLtAddRight c h

/-- Componentwise strict comparison of three angle magnitudes implies strict
comparison of their associated three-angle sums. -/
theorem angle_sum3_lt (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    {a b c A1 B1 C1 : A.Magnitude}
    (ha : A.lt a A1) (hb : A.lt b B1) (hc : A.lt c C1) :
    A.lt (A.add a (A.add b c)) (A.add A1 (A.add B1 C1)) := by
  have hbc1 : A.lt (A.add b c) (A.add B1 c) :=
    A.addLtAddRight c hb
  have hbc2 : A.lt (A.add B1 c) (A.add B1 C1) :=
    angle_add_lt_add_left S B1 hc
  have hbc : A.lt (A.add b c) (A.add B1 C1) := A.ltTrans hbc1 hbc2
  have h1 : A.lt (A.add a (A.add b c)) (A.add A1 (A.add b c)) :=
    A.addLtAddRight (A.add b c) ha
  have h2 : A.lt (A.add A1 (A.add b c)) (A.add A1 (A.add B1 C1)) :=
    angle_add_lt_add_left S A1 hbc
  exact A.ltTrans h1 h2

/-- The common proposed edge cannot be smaller than the circumradius.  Each
fixed chord would then subtend a strictly smaller central angle; summing the
three comparisons makes a full turn strictly smaller than the prescribed
three-angle sum, contradicting the hypothesis that the latter is below four
right angles. -/
theorem not_edge_lt_circumradius (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [AO : SpatialAngleOrderAxioms S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S]
    [FT : SpatialCentralAngleFullTurnAxioms S]
    [IC : InnerParallelChordConstructionAxioms S]
    [R : ParallelTriangleRatioAxioms S]
    [RI : CentralAngleRayInvarianceAxioms S]
    [W : PlaneHingeWitnessAxioms S]
    {x y z : A.Magnitude}
    {P Q R Ctr : S.Point} {pos : CircumcenterPosition}
    (h : AdmissibleTrihedralAngles S x y z)
    (hPQ : L.length P Q = C.chord x)
    (hQR : L.length Q R = C.chord y)
    (hRP : L.length R P = C.chord z)
    (hCP_CQ : L.length Ctr P = L.length Ctr Q)
    (hCP_CR : L.length Ctr P = L.length Ctr R) :
    Not (Ord.lt (E.edge x) (L.length Ctr P)) := by
  intro hedge
  have hCQ_CR : L.length Ctr Q = L.length Ctr R :=
    hCP_CQ.symm.trans hCP_CR
  have hyEdge : Ord.lt (E.edge y) (L.length Ctr Q) := by
    have hxy : E.edge x = E.edge y := E.edge_eq x y
    rw [← hxy, ← hCP_CQ]
    exact hedge
  have hzEdge : Ord.lt (E.edge z) (L.length Ctr R) := by
    have hxz : E.edge x = E.edge z := E.edge_eq x z
    rw [← hxz, ← hCP_CR]
    exact hedge
  have hxlt : A.lt (CA.centralAngle Ctr P Q) x :=
    fixedChordRadiusAngleMonotonicity S hCP_CQ hPQ hedge
  have hylt : A.lt (CA.centralAngle Ctr Q R) y :=
    fixedChordRadiusAngleMonotonicity S hCQ_CR hQR hyEdge
  have hzlt : A.lt (CA.centralAngle Ctr R P) z := by
    have hRP_radii : L.length Ctr R = L.length Ctr P := hCP_CR.symm
    exact fixedChordRadiusAngleMonotonicity S hRP_radii hRP hzEdge
  have hsum : A.lt
      (A.add (CA.centralAngle Ctr P Q)
        (A.add (CA.centralAngle Ctr Q R) (CA.centralAngle Ctr R P)))
      (A.add x (A.add y z)) :=
    angle_sum3_lt S hxlt hylt hzlt
  have hfull := FT.sum_four_right (pos := pos) hCP_CQ hCP_CR
  rw [hfull] at hsum
  have hbad : A.lt
      (A.add (A.add A.right A.right) (A.add A.right A.right))
      (A.add (A.add A.right A.right) (A.add A.right A.right)) :=
    A.ltTrans hsum h.2.2.2
  exact angle_lt_irrefl S _ hbad

/-- XI.23 circumradius bound derived from Euclidean magnitude trichotomy, the
proved equality exclusion, and the remaining I.25 comparison stage. -/
theorem circumradius_lt_edge (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [AO : SpatialAngleOrderAxioms S]
    [C : EqualRadiusChordGeometry S]
    [E : TrihedralCommonEdgeGeometry S]
    [CA : SpatialChordCentralAngleAxioms S]
    [FT : SpatialCentralAngleFullTurnAxioms S]
    [IC : InnerParallelChordConstructionAxioms S]
    [R : ParallelTriangleRatioAxioms S]
    [RI : CentralAngleRayInvarianceAxioms S]
    [W : PlaneHingeWitnessAxioms S]
    {x y z : A.Magnitude}
    {P Q R Ctr : S.Point} {pos : CircumcenterPosition}
    (h : AdmissibleTrihedralAngles S x y z)
    (hPQ : L.length P Q = C.chord x)
    (hQR : L.length Q R = C.chord y)
    (hRP : L.length R P = C.chord z)
    (hCP_CQ : L.length Ctr P = L.length Ctr Q)
    (hCP_CR : L.length Ctr P = L.length Ctr R) :
    Ord.lt (L.length Ctr P) (E.edge x) := by
  have hne : L.length Ctr P ≠ E.edge x :=
    circumradius_ne_edge S (pos := pos) h hPQ hQR hRP hCP_CQ hCP_CR
  have hnot : Not (Ord.lt (E.edge x) (L.length Ctr P)) :=
    not_edge_lt_circumradius S (pos := pos) h hPQ hQR hRP hCP_CQ hCP_CR
  rcases Euclid.Book5.MagnitudeAxioms.ltTrichotomy
      (L.length Ctr P) (E.edge x) with hlt | heq | hgt
  · exact (Ord.lt_iff_book5 _ _).2 hlt
  · exact False.elim (hne heq)
  · exact False.elim (hnot ((Ord.lt_iff_book5 _ _).2 hgt))

/-- Generic Pythagorean/right-triangle realization along a *given* normal.
The normal itself is supplied by the XI.12 construction layer.  This class
contains only the metric existence step: if the in-plane leg is shorter than
a target hypotenuse, mark a point on the normal whose hypotenuse has that
target length. -/
class NormalRightTriangleRealizationAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S] where
  realize : forall {O P : S.Point} {p : S.Plane} {n : S.Line}
      {edgeLen : L.Magnitude},
    S.onPlane O p -> S.onPlane P p ->
    S.onLine O n -> PerpendicularToPlane n p ->
    Ord.lt (L.length O P) edgeLen ->
    exists V : S.Point,
      S.onLine V n /\
      Not (S.onPlane V p) /\
      L.length V P = edgeLen

/-- Equal-radius transfer along a common normal. -/
class NormalEqualRadiusTransferAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] : Prop where
  equalHypotenuse : forall
      {V O P Q : S.Point} {n : S.Line} {p : S.Plane},
    S.onLine O n -> S.onLine V n ->
    PerpendicularToPlane n p ->
    S.onPlane O p -> S.onPlane P p -> S.onPlane Q p ->
    L.length O P = L.length O Q ->
    L.length V P = L.length V Q

/-- Derive the three equal apex distances from one height construction. -/
theorem circumcenter_normal_height (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [N : PlaneNormalConstructionAxioms S]
    [H : NormalRightTriangleRealizationAxioms S]
    [T : NormalEqualRadiusTransferAxioms S]
    {P Q R Ctr : S.Point} {p : S.Plane}
    {edgeLen : L.Magnitude}
    (hPp : S.onPlane P p) (hQp : S.onPlane Q p) (hRp : S.onPlane R p)
    (hCtrp : S.onPlane Ctr p)
    (hCP_CQ : L.length Ctr P = L.length Ctr Q)
    (hCP_CR : L.length Ctr P = L.length Ctr R)
    (hradius : Ord.lt (L.length Ctr P) edgeLen) :
    exists V : S.Point,
      Not (S.onPlane V p) /\
      L.length V P = edgeLen /\
      L.length V Q = edgeLen /\
      L.length V R = edgeLen := by
  obtain ⟨n, hOn, hnormal⟩ := N.atPoint hCtrp
  obtain ⟨V, hVn, hVoff, hVP⟩ :=
    H.realize hCtrp hPp hOn hnormal hradius
  have hVP_VQ : L.length V P = L.length V Q :=
    T.equalHypotenuse hOn hVn hnormal hCtrp hPp hQp hCP_CQ
  have hVP_VR : L.length V P = L.length V R :=
    T.equalHypotenuse hOn hVn hnormal hCtrp hPp hRp hCP_CR
  exact ⟨V, hVoff, hVP, hVP_VQ.symm.trans hVP, hVP_VR.symm.trans hVP⟩

/-- Pure incidence stage for an apex off a plane, proved from generic point-line
incidence plus XI.1-style line closure. -/
theorem offPlaneApexRays (S : SpaceGeometry)
    [J : SpatialLineIncidenceAxioms S] [I : SolidIncidenceAxioms S]
    {V P Q R : S.Point} {p : S.Plane}
    (hVoff : Not (S.onPlane V p))
    (hPp : S.onPlane P p) (hQp : S.onPlane Q p) (hRp : S.onPlane R p)
    (hPneQ : P ≠ Q) (hQneR : Q ≠ R) (hRneP : R ≠ P) :
    exists VP VQ VR : S.Line,
      VP ≠ VQ /\ VQ ≠ VR /\ VR ≠ VP /\
      S.onLine V VP /\ S.onLine P VP /\
      S.onLine V VQ /\ S.onLine Q VQ /\
      S.onLine V VR /\ S.onLine R VR := by
  have hVneP : V ≠ P := by intro h; apply hVoff; simpa [h] using hPp
  have hVneQ : V ≠ Q := by intro h; apply hVoff; simpa [h] using hQp
  have hVneR : V ≠ R := by intro h; apply hVoff; simpa [h] using hRp
  obtain ⟨VP,hVvp,hPvp⟩ := J.through hVneP
  obtain ⟨VQ,hVvq,hQvq⟩ := J.through hVneQ
  obtain ⟨VR,hVvr,hRvr⟩ := J.through hVneR
  have h12 : VP ≠ VQ := by
    intro heq
    have hQvp : S.onLine Q VP := by simpa [heq] using hQvq
    have hVPp : LineInPlane VP p := I.lineClosure hPneQ hPvp hQvp hPp hQp
    exact hVoff (hVPp V hVvp)
  have h23 : VQ ≠ VR := by
    intro heq
    have hRvq : S.onLine R VQ := by simpa [heq] using hRvr
    have hVQp : LineInPlane VQ p := I.lineClosure hQneR hQvq hRvq hQp hRp
    exact hVoff (hVQp V hVvq)
  have h31 : VR ≠ VP := by
    intro heq
    have hPvr : S.onLine P VR := by simpa [heq] using hPvp
    have hVRp : LineInPlane VR p := I.lineClosure hRneP hRvr hPvr hRp hPp
    exact hVoff (hVRp V hVvr)
  exact ⟨VP,VQ,VR,h12,h23,h31,hVvp,hPvp,hVvq,hQvq,hVvr,hRvr⟩

/-- Assemble the metric apex point and the pure incidence ray frame. -/
theorem circumcenter_apex_lift (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [N : PlaneNormalConstructionAxioms S]
    [H : NormalRightTriangleRealizationAxioms S]
    [T : NormalEqualRadiusTransferAxioms S]
    [J : SpatialLineIncidenceAxioms S]
    [I : SolidIncidenceAxioms S]
    {P Q R Ctr : S.Point} {p : S.Plane}
    {edgeLen : L.Magnitude}
    (hPp : S.onPlane P p) (hQp : S.onPlane Q p) (hRp : S.onPlane R p)
    (hCtrp : S.onPlane Ctr p)
    (hPneQ : P ≠ Q) (hQneR : Q ≠ R) (hRneP : R ≠ P)
    (hCP_CQ : L.length Ctr P = L.length Ctr Q)
    (hCP_CR : L.length Ctr P = L.length Ctr R)
    (hradius : Ord.lt (L.length Ctr P) edgeLen) :
    exists V : S.Point, exists VP VQ VR : S.Line,
      VP ≠ VQ /\ VQ ≠ VR /\ VR ≠ VP /\
      S.onLine V VP /\ S.onLine P VP /\
      S.onLine V VQ /\ S.onLine Q VQ /\
      S.onLine V VR /\ S.onLine R VR /\
      L.length V P = edgeLen /\
      L.length V Q = edgeLen /\
      L.length V R = edgeLen := by
  obtain ⟨V, hVoff, hVP, hVQ, hVR⟩ :=
    circumcenter_normal_height S hPp hQp hRp hCtrp
      hCP_CQ hCP_CR hradius
  obtain ⟨VP, VQ, VR, h12, h23, h31,
      hVvp, hPvp, hVvq, hQvq, hVvr, hRvr⟩ :=
    offPlaneApexRays S hVoff hPp hQp hRp hPneQ hQneR hRneP
  exact ⟨V, VP, VQ, VR, h12, h23, h31,
    hVvp, hPvp, hVvq, hQvq, hVvr, hRvr, hVP, hVQ, hVR⟩

/-- SSS recovery of a face angle from its two equal sides and opposite chord.
This is the metric bridge used in the final verification stage of XI.23. -/
class EqualEdgeFaceAngleAxioms (S : SpaceGeometry)
    [A : SpatialAngleMagnitude S]
    [L : SpatialSegmentMagnitude S]
    [Ord : SpatialSegmentOrderMagnitude S]
    [C : EqualRadiusChordGeometry S] where
  recover : forall
      {x : A.Magnitude} {V P Q : S.Point} {VP VQ : S.Line},
    S.onLine V VP -> S.onLine P VP ->
    S.onLine V VQ -> S.onLine Q VQ ->
    L.length V P = L.length V Q ->
    L.length P Q = C.chord x ->
    A.angle VP VQ = x




/-- The intersection-line predicate is symmetric in its two planes. -/
theorem planeIntersection_symm {S : SpaceGeometry} {p q : S.Plane} {l : S.Line}
    (h : PlaneIntersectionIsLine p q l) : PlaneIntersectionIsLine q p l := by
  refine ⟨h.1.symm, ?_⟩
  intro x
  rw [h.2]
  constructor
  · intro hx
    exact ⟨hx.2, hx.1⟩
  · intro hx
    exact ⟨hx.2, hx.1⟩

/-- Symmetry of parallel planes follows directly from XI.Def.8. -/
theorem parallelPlanes_symm {S : SpaceGeometry} {p q : S.Plane}
    (h : ParallelPlanes p q) : ParallelPlanes q p := by
  intro hmeet
  apply h
  obtain ⟨x, hxq, hxp⟩ := hmeet
  exact ⟨x, hxp, hxq⟩

structure SpatialQuadFace (S : SpaceGeometry) where
  a : S.Point
  b : S.Point
  c : S.Point
  d : S.Point
  ab : S.Line
  bc : S.Line
  cd : S.Line
  da : S.Line
  plane : S.Plane
  a_ab : S.onLine a ab
  b_ab : S.onLine b ab
  b_bc : S.onLine b bc
  c_bc : S.onLine c bc
  c_cd : S.onLine c cd
  d_cd : S.onLine d cd
  d_da : S.onLine d da
  a_da : S.onLine a da
  ab_plane : LineInPlane ab plane
  bc_plane : LineInPlane bc plane
  cd_plane : LineInPlane cd plane
  da_plane : LineInPlane da plane

def SpatialParallelogram (S : SpaceGeometry) (f : SpatialQuadFace S) : Prop :=
  S.parallelLines f.ab f.cd ∧ S.parallelLines f.bc f.da

def EqualSimilarFaces (S : SpaceGeometry) [L : SpatialSegmentMagnitude S]
    (f g : SpatialQuadFace S) : Prop :=
  L.length f.a f.b = L.length g.a g.b ∧
  L.length f.b f.c = L.length g.b g.c ∧
  L.length f.c f.d = L.length g.c g.d ∧
  L.length f.d f.a = L.length g.d g.a ∧
  S.angleCongruent f.ab f.bc g.ab g.bc ∧
  S.angleCongruent f.bc f.cd g.bc g.cd ∧
  S.angleCongruent f.cd f.da g.cd g.da ∧
  S.angleCongruent f.da f.ab g.da g.ab

class SpatialParallelogramMetricAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] : Prop where
  oppositeSides : forall (f : SpatialQuadFace S),
    SpatialParallelogram S f ->
    L.length f.a f.b = L.length f.c f.d ∧
    L.length f.b f.c = L.length f.d f.a

structure ParallelepipedFrame (S : SpaceGeometry) where
  x0 : S.Plane
  x1 : S.Plane
  y0 : S.Plane
  y1 : S.Plane
  z0 : S.Plane
  z1 : S.Plane
  hx : ParallelPlanes x0 x1
  hy : ParallelPlanes y0 y1
  hz : ParallelPlanes z0 z1
  a : S.Point
  b : S.Point
  c : S.Point
  d : S.Point
  e : S.Point
  f : S.Point
  g : S.Point
  h : S.Point
  ab : S.Line
  bc : S.Line
  cd : S.Line
  da : S.Line
  ef : S.Line
  fg : S.Line
  gh : S.Line
  he : S.Line
  ae : S.Line
  bf : S.Line
  cg : S.Line
  dh : S.Line
  abi : PlaneIntersectionIsLine x0 z0 ab
  bci : PlaneIntersectionIsLine x0 y1 bc
  cdi : PlaneIntersectionIsLine x0 z1 cd
  dai : PlaneIntersectionIsLine x0 y0 da
  efi : PlaneIntersectionIsLine x1 z0 ef
  fgi : PlaneIntersectionIsLine x1 y1 fg
  ghi : PlaneIntersectionIsLine x1 z1 gh
  hei : PlaneIntersectionIsLine x1 y0 he
  aei : PlaneIntersectionIsLine y0 z0 ae
  bfi : PlaneIntersectionIsLine y1 z0 bf
  cgi : PlaneIntersectionIsLine y1 z1 cg
  dhi : PlaneIntersectionIsLine y0 z1 dh
  a_x0 : S.onPlane a x0
  a_y0 : S.onPlane a y0
  a_z0 : S.onPlane a z0
  b_x0 : S.onPlane b x0
  b_y1 : S.onPlane b y1
  b_z0 : S.onPlane b z0
  c_x0 : S.onPlane c x0
  c_y1 : S.onPlane c y1
  c_z1 : S.onPlane c z1
  d_x0 : S.onPlane d x0
  d_y0 : S.onPlane d y0
  d_z1 : S.onPlane d z1
  e_x1 : S.onPlane e x1
  e_y0 : S.onPlane e y0
  e_z0 : S.onPlane e z0
  f_x1 : S.onPlane f x1
  f_y1 : S.onPlane f y1
  f_z0 : S.onPlane f z0
  g_x1 : S.onPlane g x1
  g_y1 : S.onPlane g y1
  g_z1 : S.onPlane g z1
  h_x1 : S.onPlane h x1
  h_y0 : S.onPlane h y0
  h_z1 : S.onPlane h z1


/-- Abstract magnitudes of planar bases and solid volumes.  Both are Euclidean
magnitudes, so Book V can compare their ratios across kinds. -/
class SpatialAreaMagnitude (S : SpaceGeometry) where
  Magnitude : Type
  magnitudeStructure : Euclid.Book5.MagnitudeStructure Magnitude
  magnitudeAxioms : Euclid.Book5.MagnitudeAxioms Magnitude

attribute [instance] SpatialAreaMagnitude.magnitudeStructure
attribute [instance] SpatialAreaMagnitude.magnitudeAxioms

class SolidMagnitude (S : SpaceGeometry) where
  Magnitude : Type
  magnitudeStructure : Euclid.Book5.MagnitudeStructure Magnitude
  magnitudeAxioms : Euclid.Book5.MagnitudeAxioms Magnitude

attribute [instance] SolidMagnitude.magnitudeStructure
attribute [instance] SolidMagnitude.magnitudeAxioms

/-- Data for a parallelepiped cut by a plane parallel to a pair of opposite
faces.  `baseLeft/baseRight` and `solidLeft/solidRight` are the magnitudes of
the two resulting bases and sub-solids. -/
structure ParallelCutParallelepiped (S : SpaceGeometry)
    [A : SpatialAreaMagnitude S] [V : SolidMagnitude S] where
  whole : ParallelepipedFrame S
  cutPlane : S.Plane
  parallelToLeft : ParallelPlanes cutPlane whole.x0
  parallelToRight : ParallelPlanes cutPlane whole.x1
  baseLeft : A.Magnitude
  baseRight : A.Magnitude
  solidLeft : V.Magnitude
  solidRight : V.Magnitude
  baseLeftPositive : Euclid.Book5.Positive baseLeft
  baseRightPositive : Euclid.Book5.Positive baseRight
  solidLeftPositive : Euclid.Book5.Positive solidLeft
  solidRightPositive : Euclid.Book5.Positive solidRight

/-- For one fixed altitude, base area determines solid magnitude by an
additive order embedding.  This is the reusable content behind Euclid XI.25:
cutting a prism into adjacent pieces adds both bases and solids, and comparison
of bases is faithfully reflected by comparison of the corresponding solids. -/
structure SameAltitudeVolumeEmbedding (S : SpaceGeometry)
    [A : SpatialAreaMagnitude S] [V : SolidMagnitude S] where
  toSolid : A.Magnitude -> V.Magnitude
  map_zero : toSolid Euclid.Book5.Zero = Euclid.Book5.Zero
  map_add : forall x y,
    toSolid (Euclid.Book5.Add x y) =
      Euclid.Book5.Add (toSolid x) (toSolid y)
  lt_iff : forall {x y},
    Euclid.Book5.Less x y <-> Euclid.Book5.Less (toSolid x) (toSolid y)

/-- A parallel cut together with the common-altitude volume embedding for its
family of sub-prisms.  Unlike the old multiple-comparison assumption, this
only states the local additive/order semantics from which all natural-multiple
comparisons are derived. -/
structure ParallelCutVolumeData (S : SpaceGeometry)
    [A : SpatialAreaMagnitude S] [V : SolidMagnitude S] where
  cut : ParallelCutParallelepiped S
  embedding : SameAltitudeVolumeEmbedding S
  left_image : embedding.toSolid cut.baseLeft = cut.solidLeft
  right_image : embedding.toSolid cut.baseRight = cut.solidRight

/-- An additive same-altitude volume embedding commutes with Euclid's natural
multiple operation. -/
theorem sameAltitude_map_multiple (S : SpaceGeometry)
    [A : SpatialAreaMagnitude S] [V : SolidMagnitude S]
    (E : SameAltitudeVolumeEmbedding S) (n : Nat) (x : A.Magnitude) :
    E.toSolid (Euclid.Book5.Multiple n x) =
      Euclid.Book5.Multiple n (E.toSolid x) := by
  induction n with
  | zero => exact E.map_zero
  | succ n ih =>
      simp [Euclid.Book5.Multiple, E.map_add, ih]

/-- Equality of trihedral solid angles is equality of their three corresponding
plane angles. -/
def EqualTrihedralAngles (S : SpaceGeometry)
    (t u : TrihedralAngle S) : Prop :=
  S.angleCongruent t.ray1 t.ray2 u.ray1 u.ray2 ∧
  S.angleCongruent t.ray2 t.ray3 u.ray2 u.ray3 ∧
  S.angleCongruent t.ray3 t.ray1 u.ray3 u.ray1

/-- Generic transport construction for a trihedral angle onto a prescribed
ray through a prescribed vertex.  This is the spatial analogue of I.23 and the
construction package underlying XI.26. -/
class TrihedralTransportConstructionAxioms (S : SpaceGeometry) : Prop where
  copyAtRay : forall (t : TrihedralAngle S) {a : S.Point} {ab : S.Line},
    S.onLine a ab ->
    exists u : TrihedralAngle S,
      u.vertex = a ∧ u.ray1 = ab ∧ EqualTrihedralAngles S u t


/-- Similarity of two parallelepipeds is represented by similarity of three
corresponding adjacent faces and equality of the included trihedral angle. -/
structure SimilarParallelepipedData (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] where
  source : ParallelepipedFrame S
  target : ParallelepipedFrame S
  sourceAngle : TrihedralAngle S
  targetAngle : TrihedralAngle S
  angleEq : EqualTrihedralAngles S targetAngle sourceAngle
  adjacentEdgeRatios :
    Euclid.Book5.SameRatio (L.length source.a source.b) (L.length source.a source.d)
      (L.length target.a target.b) (L.length target.a target.d) ∧
    Euclid.Book5.SameRatio (L.length source.a source.d) (L.length source.a source.e)
      (L.length target.a target.d) (L.length target.a target.e)

/-- The trihedral angle at vertex `a` of a parallelepiped, with rays along
its three adjacent edges AB, AD and AE. -/
def TrihedralAtFrameA (S : SpaceGeometry) (P : ParallelepipedFrame S)
    (t : TrihedralAngle S) : Prop :=
  t.vertex = P.a ∧ t.ray1 = P.ab ∧ t.ray2 = P.da ∧ t.ray3 = P.ae

/-- Spatial VI.12 bridge localized to a specified ray: given three positive
segments represented by `u:v` and an existing segment `ab`, construct a point
`d` on the chosen ray so that `u:v = ab:ad`.  This is generic proportional
construction, not XI.27-specific. -/
class SpatialFourthProportionalConstructionAxioms (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] : Prop where
  onRay : forall {u0 u1 v0 v1 a b : S.Point}
      {ab ray : S.Line},
    u0 ≠ u1 -> v0 ≠ v1 -> a ≠ b ->
    S.onLine a ab -> S.onLine b ab -> S.onLine a ray ->
    exists d : S.Point,
      d ≠ a ∧ S.onLine d ray ∧
      Euclid.Book5.SameRatio (L.length u0 u1) (L.length v0 v1)
        (L.length a b) (L.length a d)

/-- Complete three adjacent edges at one vertex to a parallelepiped by drawing
parallel planes/edges.  The prescribed vertex, edge endpoints, and edge lines
are retained literally in the resulting frame. -/
class ParallelepipedCompletionAxioms (S : SpaceGeometry) : Prop where
  complete : forall (t : TrihedralAngle S)
      {b d e : S.Point},
    t.vertex ≠ b -> t.vertex ≠ d -> t.vertex ≠ e ->
    S.onLine b t.ray1 -> S.onLine d t.ray2 -> S.onLine e t.ray3 ->
    exists P : ParallelepipedFrame S,
      P.a = t.vertex ∧ P.b = b ∧ P.d = d ∧ P.e = e ∧
      P.ab = t.ray1 ∧ P.da = t.ray2 ∧ P.ae = t.ray3 ∧
      TrihedralAtFrameA S P t

/-- Abstract solid regions, used for cut-and-paste arguments from XI.28 onward. -/
class SolidRegionGeometry (S : SpaceGeometry) [V : SolidMagnitude S] where
  Region : Type
  volume : Region -> V.Magnitude
  boundaryCongruent : Region -> Region -> Prop
  disjointUnion : Region -> Region -> Region -> Prop

/-- Set-theoretic semantics for solid regions.  This layer is generic and is
used to make common-part / remainder decompositions theorem-level consequences
rather than proposition-specific construction axioms. -/
class SolidRegionSetGeometry (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] where
  contains : S.Point -> R.Region -> Prop
  inter : R.Region -> R.Region -> R.Region
  diff : R.Region -> R.Region -> R.Region
  contains_inter : forall x p q,
    contains x (inter p q) <-> contains x p ∧ contains x q
  contains_diff : forall x p q,
    contains x (diff p q) <-> contains x p ∧ Not (contains x q)
  ext : forall {p q : R.Region},
    (forall x, contains x p <-> contains x q) -> p = q
  inter_diff_partition : forall p q : R.Region,
    R.disjointUnion (inter p q) (diff p q) p


/-- Generic cutting of a solid region by a plane into its two closed
half-regions.  The partition law is independent of any Euclid proposition. -/
class SolidRegionPlaneCutGeometry (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] where
  negative : R.Region -> S.Plane -> S.Point -> R.Region
  positive : R.Region -> S.Plane -> S.Point -> R.Region
  cut_partition : forall r p ref,
    R.disjointUnion (negative r p ref) (positive r p ref) r

/-- Oriented closed-side semantics for planes.  The orientation is chosen by a
reference point not on the plane; points on the plane belong to both closed
sides.  This is generic affine 3-space structure, independent of Book XI. -/
class PlaneHalfSpaceGeometry (S : SpaceGeometry) where
  sameClosedSide : S.Plane -> S.Point -> S.Point -> Prop
  oppositeClosedSide : S.Plane -> S.Point -> S.Point -> Prop
  reference_same : forall (p : S.Plane) (r : S.Point),
    sameClosedSide p r r
  onPlane_same : forall {p : S.Plane} {r x : S.Point},
    S.onPlane x p -> sameClosedSide p r x
  onPlane_opposite : forall {p : S.Plane} {r x : S.Point},
    S.onPlane x p -> oppositeClosedSide p r x
  classify : forall {p : S.Plane} {r x : S.Point},
    sameClosedSide p r x \/ oppositeClosedSide p r x
  offPlane_disjoint : forall {p : S.Plane} {r x : S.Point},
    Not (S.onPlane x p) ->
    Not (sameClosedSide p r x ∧ oppositeClosedSide p r x)

/-- Pointwise semantics of the generic plane cut relative to a reference
point selecting the negative side. -/
class SolidRegionPlaneCutMembershipAxioms (S : SpaceGeometry)
    [V : SolidMagnitude S] [R : SolidRegionGeometry S]
    [G : SolidRegionSetGeometry S] [H : PlaneHalfSpaceGeometry S]
    [Cut : SolidRegionPlaneCutGeometry S] : Prop where
  negative_contains : forall {r : R.Region} {p : S.Plane} {ref x : S.Point},
    (G.contains x (Cut.negative r p ref) <->
      G.contains x r /\ H.sameClosedSide p ref x)
  positive_contains : forall {r : R.Region} {p : S.Plane} {ref x : S.Point},
    (G.contains x (Cut.positive r p ref) <->
      G.contains x r /\ H.oppositeClosedSide p ref x)

theorem solidRegionInter_comm (S : SpaceGeometry)
    [V : SolidMagnitude S] [R : SolidRegionGeometry S]
    [G : SolidRegionSetGeometry S] (p q : R.Region) :
    G.inter p q = G.inter q p := by
  apply G.ext
  intro x
  rw [G.contains_inter, G.contains_inter]
  constructor
  · intro h
    exact ⟨h.2, h.1⟩
  · intro h
    exact ⟨h.2, h.1⟩

/-- Canonical region represented by a parallelepiped frame. -/
class ParallelepipedRegionGeometry (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] where
  regionOf : ParallelepipedFrame S -> R.Region

/-- Generic Euclidean volume laws: congruent bounding planes determine equal
solid magnitude, and equal pieces may be added to equal pieces. -/
class SolidRegionAxioms (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] : Prop where
  congruentBoundaryEqual : forall {p q : R.Region},
    R.boundaryCongruent p q -> R.volume p = R.volume q
  unionVolume : forall {p q w : R.Region},
    R.disjointUnion p q w ->
    Euclid.Book5.Add (R.volume p) (R.volume q) = R.volume w

/-- Four points lie on one straight line. -/
def FourPointsCollinear (S : SpaceGeometry)
    (a b c d : S.Point) : Prop :=
  exists l : S.Line,
    S.onLine a l ∧ S.onLine b l ∧ S.onLine c l ∧ S.onLine d l

/-- Euclid XI.29's geometric hypotheses in the parallelepiped frame language:
the two solids have the same base and the same opposite-plane height, while the
ends of corresponding standing edges lie on the same two straight lines. -/
def SameBaseSameHeightAligned (S : SpaceGeometry)
    (P Q : ParallelepipedFrame S) : Prop :=
  P.a = Q.a ∧ P.b = Q.b ∧ P.c = Q.c ∧ P.d = Q.d ∧
  P.x0 = Q.x0 ∧ P.x1 = Q.x1 ∧
  S.onLine Q.e P.he ∧ S.onLine Q.h P.he ∧
  S.onLine Q.f P.fg ∧ S.onLine Q.g P.fg

/-- Ordered form of XI.29's standing-edge alignment.  It records the point
order needed for Euclid's segment-subtraction step on the two top lines. -/
def SameBaseSameHeightAlignedOrdered (S : SpaceGeometry)
    (P Q : ParallelepipedFrame S) : Prop :=
  SameBaseSameHeightAligned S P Q ∧
  S.between P.e Q.e P.h ∧ S.between Q.e P.h Q.h ∧
  S.between P.f Q.f P.g ∧ S.between Q.f P.g Q.g


/-- Same base and same height for two parallelepipeds, without any alignment
assumption on the upper vertices. -/
def SameBaseSameHeight (S : SpaceGeometry)
    (P Q : ParallelepipedFrame S) : Prop :=
  P.a = Q.a ∧ P.b = Q.b ∧ P.c = Q.c ∧ P.d = Q.d ∧
  P.x0 = Q.x0 ∧ P.x1 = Q.x1

/-- Either orientation of the ordered XI.29 alignment relation. -/
def AlignedOrderedEither (S : SpaceGeometry)
    (P Q : ParallelepipedFrame S) : Prop :=
  SameBaseSameHeightAlignedOrdered S P Q ∨
  SameBaseSameHeightAlignedOrdered S Q P

/-- Incidence construction underlying XI.30.  For two same-base, same-height
parallelepipeds whose standing edges are not already aligned, construct the
intermediate parallelepiped obtained by extending the corresponding top-edge
lines.  The new solid is XI.29-aligned with each original; no volume equality
is included in this construction principle. -/
class NonAlignedBridgeConstructionAxioms (S : SpaceGeometry) : Prop where
  construct : forall (P Q : ParallelepipedFrame S),
    SameBaseSameHeight S P Q ->
    (Not (SameBaseSameHeightAligned S P Q)) ->
    exists T : ParallelepipedFrame S,
      AlignedOrderedEither S P T ∧ AlignedOrderedEither S Q T

/-- Abstract congruence witness for a planar face.  It deliberately carries
no volume information; XI.Def.10 combines five such matches to compare prisms. -/
class PolyhedralFaceGeometry (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] where
  Face : Type
  congruent : Face -> Face -> Prop
  triangle : S.Point -> S.Point -> S.Point -> Face
  quadrilateral : S.Point -> S.Point -> S.Point -> S.Point -> Face
  congruentRefl : forall f : Face, congruent f f
  congruentSymm : forall {f g : Face}, congruent f g -> congruent g f
  triangleSSS : forall {a b c d e f : S.Point},
    L.length a b = L.length d e ->
    L.length b c = L.length e f ->
    L.length c a = L.length f d ->
    congruent (triangle a b c) (triangle d e f)
  quadrilateralOfEqualSimilar : forall
      {a b c d e f g h : S.Point}
      {ab bc cd da ef fg gh he : S.Line},
    S.onLine a ab -> S.onLine b ab ->
    S.onLine b bc -> S.onLine c bc ->
    S.onLine c cd -> S.onLine d cd ->
    S.onLine d da -> S.onLine a da ->
    S.onLine e ef -> S.onLine f ef ->
    S.onLine f fg -> S.onLine g fg ->
    S.onLine g gh -> S.onLine h gh ->
    S.onLine h he -> S.onLine e he ->
    L.length a b = L.length e f ->
    L.length b c = L.length f g ->
    L.length c d = L.length g h ->
    L.length d a = L.length h e ->
    S.angleCongruent ab bc ef fg ->
    S.angleCongruent bc cd fg gh ->
    S.angleCongruent cd da gh he ->
    S.angleCongruent da ab he ef ->
    congruent (quadrilateral a b c d) (quadrilateral e f g h)

/-- Transport XI.24's equal-and-similar quadrilateral-face data into the
polyhedral face-congruence layer used by XI.28-29. -/
theorem polyhedralQuadCongruent_of_equalSimilar
    (S : SpaceGeometry) [L : SpatialSegmentMagnitude S]
    [F : PolyhedralFaceGeometry S]
    (p q : SpatialQuadFace S) (h : EqualSimilarFaces S p q) :
    F.congruent (F.quadrilateral p.a p.b p.c p.d)
      (F.quadrilateral q.a q.b q.c q.d) := by
  apply F.quadrilateralOfEqualSimilar
  · exact p.a_ab
  · exact p.b_ab
  · exact p.b_bc
  · exact p.c_bc
  · exact p.c_cd
  · exact p.d_cd
  · exact p.d_da
  · exact p.a_da
  · exact q.a_ab
  · exact q.b_ab
  · exact q.b_bc
  · exact q.c_bc
  · exact q.c_cd
  · exact q.d_cd
  · exact q.d_da
  · exact q.a_da
  · exact h.1
  · exact h.2.1
  · exact h.2.2.1
  · exact h.2.2.2.1
  · exact h.2.2.2.2.1
  · exact h.2.2.2.2.2.1
  · exact h.2.2.2.2.2.2.1
  · exact h.2.2.2.2.2.2.2

/-- A triangular prism is bounded by two triangular faces and three
parallelogram faces.  This is the exact five-face package used in XI.28-29. -/
structure TriangularPrismBoundary (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S] where
  end1 : F.Face
  end2 : F.Face
  side1 : F.Face
  side2 : F.Face
  side3 : F.Face

/-- Pairwise congruence of the five corresponding faces of two triangular
prisms. -/
def CongruentPrismBoundaries (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (p q : TriangularPrismBoundary S) : Prop :=
  F.congruent p.end1 q.end1 ∧
  F.congruent p.end2 q.end2 ∧
  F.congruent p.side1 q.side1 ∧
  F.congruent p.side2 q.side2 ∧
  F.congruent p.side3 q.side3

/-- Generic XI.Def.10 realization: a region carrying a prism boundary is
congruent to another region when all five corresponding bounding faces are
congruent.  This is independent of XI.28 and XI.29. -/
class PrismBoundaryRealizationAxioms
    (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S]
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S] where
  realizes : R.Region -> TriangularPrismBoundary S -> Prop
  boundaryCongruentOfFaces : forall {r s : R.Region}
      {p q : TriangularPrismBoundary S},
    realizes r p -> realizes s q -> CongruentPrismBoundaries S p q ->
    R.boundaryCongruent r s

/-- The two concrete triangular-prism boundaries obtained by cutting a
parallelepiped along the corresponding diagonals AC and EG. -/
def diagonalLeftBoundary (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (P : ParallelepipedFrame S) : TriangularPrismBoundary S := {
  end1 := F.triangle P.a P.b P.c
  end2 := F.triangle P.e P.f P.g
  side1 := F.quadrilateral P.a P.b P.f P.e
  side2 := F.quadrilateral P.b P.c P.g P.f
  side3 := F.quadrilateral P.a P.c P.g P.e
}

def diagonalRightBoundary (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (P : ParallelepipedFrame S) : TriangularPrismBoundary S := {
  end1 := F.triangle P.c P.d P.a
  end2 := F.triangle P.g P.h P.e
  side1 := F.quadrilateral P.d P.c P.g P.h
  side2 := F.quadrilateral P.a P.d P.h P.e
  side3 := F.quadrilateral P.a P.c P.g P.e
}

/-- Affine diagonal-plane fact for a parallelepiped: A,C,E,G are coplanar,
and the remaining vertices B,D lie on opposite sides.  This is a reusable
parallelepiped fact, not tied to XI.28's volume conclusion. -/
class ParallelepipedDiagonalPlaneAxioms (S : SpaceGeometry)
    [H : PlaneHalfSpaceGeometry S] : Prop where
  diagonalPlane : forall (P : ParallelepipedFrame S),
    exists p : S.Plane,
      S.onPlane P.a p ∧ S.onPlane P.c p ∧
      S.onPlane P.e p ∧ S.onPlane P.g p ∧
      H.oppositeClosedSide p P.b P.d

/-- Generic realization of the two triangular prisms produced by cutting a
parallelepiped through the AC/EG diagonal plane.  The cut operation and its
partition law are generic; this theorem only identifies the two resulting
polyhedral boundaries. -/
class ParallelepipedDiagonalPrismAxioms
    (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] [G : SolidRegionSetGeometry S]
    [PR : ParallelepipedRegionGeometry S]
    [H : PlaneHalfSpaceGeometry S] [Cut : SolidRegionPlaneCutGeometry S]
    [CM : SolidRegionPlaneCutMembershipAxioms S]
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    [B : PrismBoundaryRealizationAxioms S] : Prop where
  realizes : forall (P : ParallelepipedFrame S) {p : S.Plane},
    S.onPlane P.a p -> S.onPlane P.c p ->
    S.onPlane P.e p -> S.onPlane P.g p ->
    H.oppositeClosedSide p P.b P.d ->
    B.realizes (Cut.negative (PR.regionOf P) p P.b) (diagonalLeftBoundary S P) ∧
    B.realizes (Cut.positive (PR.regionOf P) p P.b) (diagonalRightBoundary S P)

/-- Raw SSS data identifying two triangular faces.  This contains only
point/length information; face congruence is derived below via I.8/SSS. -/
structure TriangleFaceSSSWitness (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (left right : F.Face) where
  a : S.Point
  b : S.Point
  c : S.Point
  d : S.Point
  e : S.Point
  f : S.Point
  left_eq : left = F.triangle a b c
  right_eq : right = F.triangle d e f
  side1 : L.length a b = L.length d e
  side2 : L.length b c = L.length e f
  side3 : L.length c a = L.length f d

/-- Raw metric/incidence data identifying two equal-similar quadrilateral
faces.  Congruence is derived through the generic quadrilateral bridge. -/
structure QuadFaceEqualSimilarWitness (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (left right : F.Face) where
  a : S.Point
  b : S.Point
  c : S.Point
  d : S.Point
  e : S.Point
  f : S.Point
  g : S.Point
  h : S.Point
  ab : S.Line
  bc : S.Line
  cd : S.Line
  da : S.Line
  ef : S.Line
  fg : S.Line
  gh : S.Line
  he : S.Line
  left_eq : left = F.quadrilateral a b c d
  right_eq : right = F.quadrilateral e f g h
  a_ab : S.onLine a ab
  b_ab : S.onLine b ab
  b_bc : S.onLine b bc
  c_bc : S.onLine c bc
  c_cd : S.onLine c cd
  d_cd : S.onLine d cd
  d_da : S.onLine d da
  a_da : S.onLine a da
  e_ef : S.onLine e ef
  f_ef : S.onLine f ef
  f_fg : S.onLine f fg
  g_fg : S.onLine g fg
  g_gh : S.onLine g gh
  h_gh : S.onLine h gh
  h_he : S.onLine h he
  e_he : S.onLine e he
  len1 : L.length a b = L.length e f
  len2 : L.length b c = L.length f g
  len3 : L.length c d = L.length g h
  len4 : L.length d a = L.length h e
  ang1 : S.angleCongruent ab bc ef fg
  ang2 : S.angleCongruent bc cd fg gh
  ang3 : S.angleCongruent cd da gh he
  ang4 : S.angleCongruent da ab he ef

theorem triangleFaceCongruent_of_witness (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    {left right : F.Face} (W : TriangleFaceSSSWitness S left right) :
    F.congruent left right := by
  have h : F.congruent (F.triangle W.a W.b W.c) (F.triangle W.d W.e W.f) :=
    F.triangleSSS W.side1 W.side2 W.side3
  simpa only [W.left_eq, W.right_eq] using h

theorem quadFaceCongruent_of_witness (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    {left right : F.Face} (W : QuadFaceEqualSimilarWitness S left right) :
    F.congruent left right := by
  have h : F.congruent (F.quadrilateral W.a W.b W.c W.d)
      (F.quadrilateral W.e W.f W.g W.h) :=
    F.quadrilateralOfEqualSimilar
      W.a_ab W.b_ab W.b_bc W.c_bc W.c_cd W.d_cd W.d_da W.a_da
      W.e_ef W.f_ef W.f_fg W.g_fg W.g_gh W.h_gh W.h_he W.e_he
      W.len1 W.len2 W.len3 W.len4 W.ang1 W.ang2 W.ang3 W.ang4
  simpa only [W.left_eq, W.right_eq] using h

/-- Canonical left remainder prism in XI.29.  Its two triangular ends lie
at the left/front base vertices, two side faces are inherited from P and Q,
and the fifth face is the top strip between their corresponding top edges. -/
def alignedLeftRemainderBoundary (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (P Q : ParallelepipedFrame S) : TriangularPrismBoundary S := {
  end1 := F.triangle P.a P.e Q.e
  end2 := F.triangle P.b P.f Q.f
  side1 := F.quadrilateral P.a P.b P.f P.e
  side2 := F.quadrilateral Q.a Q.b Q.f Q.e
  side3 := F.quadrilateral P.e P.f Q.f Q.e
}

/-- Canonical right remainder prism in XI.29. -/
def alignedRightRemainderBoundary (S : SpaceGeometry)
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    (P Q : ParallelepipedFrame S) : TriangularPrismBoundary S := {
  end1 := F.triangle P.d P.h Q.h
  end2 := F.triangle P.c P.g Q.g
  side1 := F.quadrilateral P.d P.c P.g P.h
  side2 := F.quadrilateral Q.d Q.c Q.g Q.h
  side3 := F.quadrilateral P.h P.g Q.g Q.h
}

/-- Generic geometric description of the differences of two ordered
sheared parallelepipeds on the same base and between the same parallel planes.
The set differences themselves come from `SolidRegionSetGeometry`; this layer
only identifies their polyhedral boundaries as triangular prisms. -/
class ShearedParallelepipedDifferencePrismAxioms
    (S : SpaceGeometry) [V : SolidMagnitude S]
    [R : SolidRegionGeometry S] [G : SolidRegionSetGeometry S]
    [PR : ParallelepipedRegionGeometry S]
    [L : SpatialSegmentMagnitude S] [F : PolyhedralFaceGeometry S]
    [B : PrismBoundaryRealizationAxioms S] : Prop where
  realizes : forall (P Q : ParallelepipedFrame S),
    SameBaseSameHeightAlignedOrdered S P Q ->
    B.realizes (G.diff (PR.regionOf P) (PR.regionOf Q))
        (alignedLeftRemainderBoundary S P Q) ∧
      B.realizes (G.diff (PR.regionOf Q) (PR.regionOf P))
        (alignedRightRemainderBoundary S P Q)

end Euclid.Book11
